### ISSUE TITLE
Incorrect Google Chrome Version

### ISSUE THREAD

**Issue by Carthanial** [Tengda-He/kibana#121]
### Description : 
- chromeDriver is version 74 and Chrome v94 is being used causing an error at Functional Test stage. 

#### Next Steps : 
- Either downgrade Google Chrome or upgrade chromeDriver versions

##### Reference : Job [#58](https://jenkins.bfs.sichend.people.aws.dev/blue/organizations/jenkins/Kibana/detail/bfs6.7.2_test/58/pipeline/66)

**Comment by Carthanial** [comment]
### Update : 
> Upgrading chromedriver version to 94.0.0 to match chrome version in dockerfile leads to : 
-  chromedriver being incompatable with node v10.15.2 due to its dependency `extract@zip@2.0.1` requiring node v10.17.0
#### Proposed fix : 
- The two options we have here are to either upgrade node to v10.17.0 or to downgrade the chrome version to match the original chromedriver version of v74.
- My opinion is upgrading node will likely cause many more breaks and add far more time to the project and therefore I propose we downgrade Chrome to match the chromedriver version

##### Reference : Job [#69](https://jenkins.bfs.sichend.people.aws.dev/blue/organizations/jenkins/Kibana/detail/bfs6.7.2_test/69/pipeline)

**Comment by zhyuanqi** [comment]
Let's downgrade chrome. Try use chrome and chromedriver and 79 and see if it works
