### ISSUE TITLE
Failing Unit Test Causing Unstable Build 

### ISSUE THREAD

**Issue by Carthanial** [Tengda-He/kibana#26]
# Unit Test Unstable Build 

### Failing Test Script

`FAIL src/dev/build/lib/scan_copy.test.ts
  ● copies files and directories from source to dest, including dot files, creating dest if necessary, respecting mode

    expect(received).toBe(expected) // Object.is equality

    Expected: "644"
    Received: "664"

      94 |   );
      95 | 
    > 96 |   expect(getCommonMode(resolve(destination, 'foo_dir/bar.txt'))).toBe(IS_WINDOWS ? '666' : '644');
         |                                                                  ^
      97 | });
      98 | 
      99 | it('applies filter function specified', async () => {

      at Object.<anonymous>.it (src/dev/build/lib/scan_copy.test.ts:96:66)`

**Comment by Tengda-He** [comment]
can we have a PR skip this then?

**Comment by 2samueld** [comment]
PR created; test issue skipped.
