### ISSUE TITLE
Downgrade Chrome and Chrome Driver

### ISSUE THREAD

**Issue by 2samueld** [Tengda-He/kibana#94]
# Description

bfs6.5.4 is using node v8. The current chrome and chromedriver version doesn't support node v8. Chrome has to be downgrade to <= v79.

Link for chrome node v8 support: https://github.com/giggio/node-chromedriver/blob/79.0.0/azure-pipelines.yml

**Comment by Tengda-He** [comment]
have you figured out which chromedriver will use and need to upload S3?

**Comment by sichend** [comment]
In your docker file, you need to use the following line to install the required softwares 

```
RUN curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && apt-get update && apt-get install -y rsync jq bsdtar --no-install-recommends && wget -O /tmp/chrome-linux.zip "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F706915%2Fchrome-linux.zip?generation=1571324979333057&alt=media" && unzip /tmp/chrome-linux.zip -d /tmp/ && cp /tmp/chrome-linux/chrome /usr/bin/google-chrome && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

**Comment by 2samueld** [comment]
> have you figured out which chromedriver will use and need to upload S3?

It'll be using chrome v79

**Comment by zhyuanqi** [comment]
I was checking on pipeline bfs6.5.4_test https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs6.5.4_test/. The newest run, you are still using
```
curl https://storage.googleapis.com/kibana-ci-es-snapshots-permanent/6.8.10/elasticsearch-6.8.10-SNAPSHOT.tar.gz --output elasticsearch.tar.gz"
```
Why do you need a elasticsearch 6.8 in bfs 6.5
I believe we talked about using S3 bucket. Sichen already posted a solution here https://github.com/Tengda-He/kibana/issues/34#issuecomment-987300010 on Monday which is two days ago. He also gave an example run with code implemented. If you check on the email, you should not miss this part
I don’t know why you start the google chrome while ES is not ready.
